name    = "mfi"
version = "0.0.1"
license = "MIT"
author  = "Ian Giestas Pauli"
maintainer = "iangiestas@usp.br"

[library]
build-script="Makefile"

[build]
link = ["blas","lapack"]

[preprocess.cpp]
macros = ["MFI_EXTENSIONS", "MFI_LINK_EXTERNAL"]

[features]
with-cublas.build.link = ["blas", "lapack", "cublas", "cudart"]
with-cublas.preprocess.cpp.macros = ["MFI_CUBLAS"]

[profiles]
cublas = ["with-cublas"]

