name    = "mfi"
version = "0.0.1"
license = "MIT"
author  = "Ian Giestas Pauli"
maintainer = "iangiestas@usp.br"

[library]
build-script="Makefile"

[build]
link = ["blas", "lapack"]

[preprocess.cpp]
macros = ["MFI_EXTENSIONS", "MFI_LINK_EXTERNAL"]

[features]
cublas.preprocess.cpp.macros = ["MFI_CUBLAS"]
cublas.dependencies.openmp = "*"

[profiles]
cublas = ["cublas"]
