name    = "mfi"
version = "0.0.1"
license = "MIT"
author  = "Ian Giestas Pauli"
maintainer = "iangiestas@usp.br"

[library]
build-script="Makefile"

[build]
link = ["blas","lapack","cublas","cudart"]

[[test]]
name = "test_cublas_gemv"
main = "test_gemv_check.f90"
