#:def axpy(f77,f90,mfi,pfxs,suffix='')
#:set wp = pfxs[0]
subroutine test_${f77 + suffix}$
    use f77_blas, only: ${f77}$, ${f90}$
    use mfi_blas, only: ${mfi}$, mfi_${f77}$
#:if suffix
    call mfi_force_gpu()
#:endif

    integer, parameter :: wp = ${kind(wp)}$
    integer, parameter :: N = 20
    ${type(wp)}$ :: x(N), y(N), x_in(N), y_in(N), x_rf(N), y_rf(N)
    ${type(wp)}$ :: alpha

    $:test_seed()
    $:random_number(type(wp),'x','(N)')
    $:random_number(type(wp),'y','(N)')
    $:random_number(type(wp),'alpha')

    x_in = x; y_in = y
    call ${f77}$(N, alpha, x_in, 1, y_in, 1)
    x_rf = x_in; y_rf = y_in

    x_in = x; y_in = y
    call ${f90}$(N, alpha, x_in, 1, y_in, 1)
    $:assert_close_1d('x_in', 'x_rf', '${f90}$:x', wp)
    $:assert_close_1d('y_in', 'y_rf', '${f90}$:y', wp)

    x_in = x; y_in = y
    call mfi_${f77}$(x_in, y_in, alpha)
    $:assert_close_1d('x_in', 'x_rf', 'mfi_${f77}$:x', wp)
    $:assert_close_1d('y_in', 'y_rf', 'mfi_${f77}$:y', wp)

    x_in = x; y_in = y
    call ${mfi}$(x_in, y_in, alpha)
    $:assert_close_1d('x_in', 'x_rf', '${mfi}$:x', wp)
    $:assert_close_1d('y_in', 'y_rf', '${mfi}$:y', wp)

end subroutine
#:enddef
