#:def iamin_iamax(f77,f90,mfi,pfxs,suffix='')
#:set wp = pfxs[0]
#:set f77_name = 'i' + f77[1:] + f77[0]
subroutine test_${f77_name + suffix}$
    use f77_blas, only: ${f77_name}$, ${f90}$
    use mfi_blas, only: ${mfi}$, mfi_${f77_name}$

    integer, parameter :: wp = ${kind(wp)}$
    integer :: N, ii
    ${type(wp)}$, allocatable :: array(:)
    integer :: res(4)

#:if suffix
    call mfi_force_gpu()
#:endif

    $:test_seed()
    call test_get_1d(10000000, N)

    allocate(array(N))
        array(ii) = real(ii, wp)
    end do
    res(1) = ${f77_name}$(N, array, 1)
    res(2) = mfi_${f77_name}$(array)
    res(3) = ${f90}$(N, array, 1)
    res(4) = ${mfi}$(array)
    call assert(all(res == res(1)), "sequential array mismatch")

    $:random_number(type(wp), 'array', '(N)')
    res(1) = ${f77_name}$(N, array, 1)
    res(2) = ${f90}$(N, array, 1)
    res(3) = mfi_${f77_name}$(array)
    res(4) = ${mfi}$(array)
    call assert(all(res == res(1)), "random array mismatch")

end subroutine
#:enddef
