#:def iamin_iamax(f77,f90,mfi,pfxs)
#:set wp = pfxs[0]
subroutine test_${f77}$
    use f77_blas, only: ${f77}$, ${f90}$
    use mfi_blas, only: ${mfi}$, mfi_${f77}$

    integer, parameter :: wp = ${kind(wp)}$
    integer, parameter :: N = 20
    ${type(wp)}$ :: array(N)
    integer :: res(4)
    integer :: ii

    $:test_seed()

    do ii = 1, N
        array(ii) = real(ii, wp)
    end do
    res(1) = ${f77}$(N, array, 1)
    res(2) = mfi_${f77}$(array)
    res(3) = ${f90}$(N, array, 1)
    res(4) = ${mfi}$(array)
    call assert(all(res == res(1)), "sequential array mismatch")

    $:random_number(type(wp), 'array', '(N)')
    res(1) = ${f77}$(N, array, 1)
    res(2) = ${f90}$(N, array, 1)
    res(3) = mfi_${f77}$(array)
    res(4) = ${mfi}$(array)
    call assert(all(res == res(1)), "random array mismatch")

end subroutine
#:enddef
