#:def lamch(f77,f90,mfi,pfxs,suffix='')
#:set wp = pfxs[0]
#:set _opts = "['E','e','S','s','B','b','P','p','N','n','R','r','M','m','U','u','L','l','O','o']"
subroutine test_${f77 + suffix}$
    use f77_blas, only: ${f77}$
    use mfi_blas, only: ${mfi}$, mfi_force_gpu

    integer, parameter :: wp = ${kind(wp)}$
    character, parameter :: options(*) = ${_opts}$
    ${type(wp)}$ :: a, b
    integer :: i

#:if suffix
    call mfi_force_gpu()
#:endif

    do i=1,size(options)
        a = ${f77}$(options(i))
        b = ${mfi}$(options(i), 1.0_wp)
        call assert(abs(a - b) < sqrt(epsilon(1.0_wp)), "option " // options(i) // " mismatch")
    end do

end subroutine
#:enddef
