#:def rot(f77,f90,mfi,pfxs,suffix='')
#:set A, B = get_types(pfxs)
subroutine test_${f77 + suffix}$
    use f77_blas, only: ${f77}$, ${f90}$
    use mfi_blas, only: ${mfi}$, mfi_${f77}$
#:if suffix
    call mfi_force_gpu()
#:endif

    integer, parameter :: wp = ${kind(A)}$
    real(wp), parameter :: pi = 4.0_wp * atan(1.0_wp)
    integer, parameter :: N = 20
    ${type(A)}$ :: x(N), y(N), x_in(N), y_in(N), x_rf(N), y_rf(N)
    real(wp) :: angle
    ${real(A)}$ :: c
    ${type(B)}$ :: s

    $:test_seed()
    call random_number(angle)
    angle = angle * 2.0_wp * pi
    $:random_number(type(A),'x','(N)')
    $:random_number(type(A),'y','(N)')

    c = cos(angle)
    s = sin(angle)

    x_in = x; y_in = y
    call ${f77}$(N, x_in, 1, y_in, 1, c, s)
    x_rf = x_in; y_rf = y_in

    x_in = x; y_in = y
    call ${f90}$(N, x_in, 1, y_in, 1, c, s)
    $:assert_close_1d('x_in', 'x_rf', '${f90}$:x', A)
    $:assert_close_1d('y_in', 'y_rf', '${f90}$:y', A)

    x_in = x; y_in = y
    call mfi_${f77}$(x_in, y_in, c, s)
    $:assert_close_1d('x_in', 'x_rf', 'mfi_${f77}$:x', A)
    $:assert_close_1d('y_in', 'y_rf', 'mfi_${f77}$:y', A)

    x_in = x; y_in = y
    call ${mfi}$(x_in, y_in, c, s)
    $:assert_close_1d('x_in', 'x_rf', '${mfi}$:x', A)
    $:assert_close_1d('y_in', 'y_rf', '${mfi}$:y', A)

end subroutine
#:enddef
