#:def scal(f77,f90,mfi,pfxs,suffix='')
#:set A, B = get_types(pfxs)
subroutine test_${f77 + suffix}$
    use f77_blas, only: ${f77}$, ${f90}$
    use mfi_blas, only: ${mfi}$, mfi_${f77}$, mfi_force_gpu, mfi_force_cpu

    integer, parameter :: wp = ${kind(A)}$
    integer :: N
    ${type(A)}$, allocatable :: x(:), x_in(:), x_rf(:)
    ${type(B)}$ :: alpha

#:if suffix
    call mfi_force_gpu()
#:endif
    $:test_seed()
    call test_get_1d(2000, N)

    allocate(x(N), x_in(N), x_rf(N))
    $:random_number(type(A),'x','(N)')
    $:random_number(type(B),'alpha')

    x_in = x
    call ${f77}$(N, alpha, x_in, 1)
    x_rf = x_in

    x_in = x
    call ${f90}$(N, alpha, x_in, 1)
    @:assert_close_1d(x_in, x_rf, '${f90}$', ${A}$)

    x_in = x
    call mfi_${f77}$(alpha, x_in)
    @:assert_close_1d(x_in, x_rf, 'mfi_${f77}$', ${A}$)

    x_in = x
    call ${mfi}$(alpha, x_in)
    @:assert_close_1d(x_in, x_rf, '${mfi}$', ${A}$)

    deallocate(x, x_in, x_rf)

    call mfi_force_cpu()
end subroutine
#:enddef
