#:def scal(f77,f90,mfi,pfxs)
#:set A, B = get_types(pfxs)
subroutine test_${f77}$
    use f77_blas, only: ${f77}$, ${f90}$
    use mfi_blas, only: ${mfi}$, mfi_${f77}$

    integer, parameter :: wp = ${kind(A)}$
    integer, parameter :: N = 20
    ${type(A)}$ :: x(N), x_in(N), x_rf(N)
    ${type(B)}$ :: alpha

    $:test_seed()
    $:random_number(type(A),'x','(N)')
    $:random_number(type(B),'alpha')

    x_in = x
    call ${f77}$(N, alpha, x_in, 1)
    x_rf = x_in

    x_in = x
    call ${f90}$(N, alpha, x_in, 1)
    $:assert_close_1d('x_in', 'x_rf', '${f90}$', A)

    x_in = x
    call mfi_${f77}$(alpha, x_in)
    $:assert_close_1d('x_in', 'x_rf', 'mfi_${f77}$', A)

    x_in = x
    call ${mfi}$(alpha, x_in)
    $:assert_close_1d('x_in', 'x_rf', '${mfi}$', A)

end subroutine
#:enddef
