#:def trsm(f77,f90,mfi,pfxs,suffix='')
#:set wp = pfxs[0]
subroutine test_${f77 + suffix}$
    use f77_blas, only: ${f77}$, ${f90}$
    use mfi_blas, only: ${mfi}$

    integer, parameter :: wp = ${kind(wp)}$
    integer, parameter :: M = 10, N = 10
    ${type(wp)}$ :: A(M,M), B(M,N), B_in(M,N), B_rf(M,N)
    ${type(wp)}$ :: alpha
    character :: side, uplo, transa, diag
    integer :: i_side, i_uplo, i_transa, i_diag

    character, parameter :: sides(*) = ['L', 'R']
    character, parameter :: uplos(*) = ['U', 'L']
    character, parameter :: transas(*) = ['N', 'T', 'C']
    character, parameter :: diags(*) = ['N', 'U']

    $:test_seed()

    A = 0.0_wp
    do i_side = 1, M
        A(i_side, i_side) = 1.0_wp + real(i_side, wp)
        do i_uplo = 1, i_side - 1
            A(i_uplo, i_side) = real(i_uplo + i_side, wp)
        end do
    end do

    $:random_number(type(wp),'B','(M,N)')
    $:random_number(type(wp),'alpha')

    do i_side = 1, size(sides)
    do i_uplo = 1, size(uplos)
    do i_transa = 1, size(transas)
    do i_diag = 1, size(diags)
        side   = sides(i_side)
        uplo   = uplos(i_uplo)
        transa = transas(i_transa)
        diag   = diags(i_diag)

        B_rf = B
        call ${f77}$(side, uplo, transa, diag, M, N, alpha, A, M, B_rf, M)

        B_in = B
        call ${mfi}$(A, B_in, side=side, uplo=uplo, transa=transa, diag=diag, alpha=alpha)
        $:assert_close('B_in', 'B_rf', '${mfi}$:${side}${uplo}${transa}${diag}', wp)

#if defined(MFI_CUBLAS)
        call mfi_force_gpu()
        B_in = B
        call ${mfi}$(A, B_in, side=side, uplo=uplo, transa=transa, diag=diag, alpha=alpha)
        call mfi_force_cpu()
        $:assert_close('B_in', 'B_rf', 'GPU:${mfi}$:${side}${uplo}${transa}${diag}', wp)
#endif

    end do
    end do
    end do
    end do
end subroutine
#:enddef
