name: docs-deployment

on:
  push:
    branches: [main, impl/cublas]
    paths: ["**.fpp", "**.fypp", "**.f90", "ford.md", "doc/**", ".github/workflows/docs-deployment.yml"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install fypp and FORD
      run: pip install --upgrade fypp ford

    - name: Generate docs
      run: |
        make
        ford ford.md

    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      with:
        BRANCH: docs
        FOLDER: api-reference
