name: fpm-deployment

on: [push, pull_request, workflow_dispatch]

env:
  PROJECT_NAME: "mfi"

jobs:
  test-and-deploy-cpu:
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install fypp
      run: pip install --upgrade fypp

    - name: Setup Fortran (GCC 13)
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: gcc
        version: "13"

    - name: Install BLAS/LAPACK
      run: sudo apt install -y libblas-dev liblapack-dev

    - name: Install fpm
      uses: fortran-lang/setup-fpm@v5
      with:
        fpm-version: 'v0.10.0'

    - name: Generate and test (CPU)
      run: |
        make FYPPFLAGS=-DMFI_EXTENSIONS
        mkdir -p ${{ env.PROJECT_NAME }}-fpm
        cp -R src test fpm.toml LICENSE ${{ env.PROJECT_NAME }}-fpm
        find ${{ env.PROJECT_NAME }}-fpm/src  -type f ! -name "*.f90" -delete
        find ${{ env.PROJECT_NAME }}-fpm/test -type f ! -name "*.f90" -delete
        fpm build --profile release

    - name: Deploy to ${{ env.PROJECT_NAME }}-fpm
      uses: JamesIves/github-pages-deploy-action@v4
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      with:
        BRANCH: ${{ env.PROJECT_NAME }}-fpm
        FOLDER: ${{ env.PROJECT_NAME }}-fpm

  test-and-deploy-cublas:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install fypp
      run: pip install --upgrade fypp

    - name: Setup Fortran (GCC 13)
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: gcc
        version: "13"

    - name: Install BLAS/LAPACK/CUDA
      run: |
        sudo apt install -y libblas-dev liblapack-dev
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt update
        sudo apt install -y cuda-toolkit-12-8

    - name: Install fpm
      uses: fortran-lang/setup-fpm@v5
      with:
        fpm-version: 'v0.10.0'

    - name: Generate (cuBLAS)
      env:
        LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib64/stubs
      run: |
        make FYPPFLAGS="-DMFI_EXTENSIONS -DMFI_USE_CUBLAS"
        mkdir -p ${{ env.PROJECT_NAME }}-cublas
        cp -R src test fpm.toml LICENSE ${{ env.PROJECT_NAME }}-cublas
        find ${{ env.PROJECT_NAME }}-cublas/src  -type f ! -name "*.f90" -delete
        find ${{ env.PROJECT_NAME }}-cublas/test -type f ! -name "*.f90" -delete

    - name: Deploy to mfi-cublas
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        BRANCH: mfi-cublas
        FOLDER: ${{ env.PROJECT_NAME }}-cublas
