name: fpm-deployment

on: [push, pull_request, workflow_dispatch]

env:
  PROJECT_NAME: "mfi"

jobs:
  exhaustive-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [cpu-only, gpu-ready]
        fpm-profile: [release, cublas]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install fypp
      run: pip install --upgrade fypp

    - name: Generate sources
      run: make

    - name: Run exhaustive tests
      run: |
        nix-shell shells/${{ matrix.environment }}.nix --run "fortran-fpm test --profile ${{ matrix.fpm-profile }}"

  deploy-artifacts:
    needs: exhaustive-test
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install fypp
      run: pip install --upgrade fypp

    - name: Generate sources
      run: make

    - name: Prepare mfi-fpm
      run: |
        mkdir -p ${{ env.PROJECT_NAME }}-fpm
        cp -R src test fpm.toml LICENSE ${{ env.PROJECT_NAME }}-fpm
        find ${{ env.PROJECT_NAME }}-fpm/src  -type f ! -name "*.f90" ! -name "*.c" -delete
        find ${{ env.PROJECT_NAME }}-fpm/test -type f ! -name "*.f90" -delete

    - name: Deploy to mfi-fpm
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: mfi-fpm
        folder: ${{ env.PROJECT_NAME }}-fpm
        clean: true

    - name: Prepare mfi-cublas
      run: |
        mkdir -p ${{ env.PROJECT_NAME }}-cublas
        cp -R src test fpm.toml LICENSE ${{ env.PROJECT_NAME }}-cublas
        find ${{ env.PROJECT_NAME }}-cublas/src  -type f ! -name "*.f90" ! -name "*.c" -delete
        find ${{ env.PROJECT_NAME }}-cublas/test -type f ! -name "*.f90" -delete

    - name: Deploy to mfi-cublas
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: mfi-cublas
        folder: ${{ env.PROJECT_NAME }}-cublas
        clean: true
